export enum GetLiftypesActionTypes {
    GET_LIFTTYPES = "GET_LIFTTYPES",
    GET_LIFTTYPES_FAILED = "GET_LIFTTYPES_FAILED",
    GET_LIFTTYPES_SUCCESS = "GET_LIFTTYPES_SUCCESS"
}

export enum CreateLiftypesActionTypes {
    CREATE_LIFTTYPES = "CREATE_LIFTTYPES",
    CREATE_LIFTTYPES_FAILED = "CREATE_LIFTTYPES_FAILED",
    CREATE_LIFTTYPES_SUCCESS = "CREATE_LIFTTYPES_SUCCESS"
}


export enum UpdateLiftypesActionTypes {
    UPDATE_LIFTTYPES = "UPDATE_LIFTTYPES",
    UPDATE_LIFTTYPES_FAILED = "UPDATE_LIFTTYPES_FAILED",
    UPDATE_LIFTTYPES_SUCCESS = "UPDATE_LIFTTYPES_SUCCESS"
}


export enum DeleteLiftypesActionTypes {
    DELETE_LIFTTYPES = "DELETE_LIFTTYPES",
    DELETE_LIFTTYPES_FAILED = "DELETE_LIFTTYPES_FAILED",
    DELETE_LIFTTYPES_SUCCESS = "DELETE_LIFTTYPES_SUCCESS"
}