export enum BookingsReviewActionTypes {
    BOOKINGS_REVIEW = "BOOKINGS_REVIEW",
    BOOKINGS_REVIEW_FAILED = "BOOKINGS_REVIEW_FAILED",
    UPDATE_BOOKING = "UPDATE_BOOKING",
    UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS",
    UPDATE_BOOKING_FAILED = "UPDATE_BOOKING_FAILED"
}