export enum CompanyActionTypes{
    GET_COMPANY = "GET_COMPANY",
    GET_COMPANY_FAILED = "GET_COMPANY_FAILED",
    GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS",

    CREATE_COMPANY = "CREATE_COMPANY",
    CREATE_COMPANY_FAILED = "CREATE_COMPANY_FAILED",
    CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS",

    DELETE_COMPANY = "DELETE_COMPANY",
    DELETE_COMPANY_FAILED = "DELETE_COMPANY_FAILED",
    DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS",

    EDIT_COMPANY = "EDIT_COMPANY",
    EDIT_COMPANY_FAILED = "EDIT_COMPANY_FAILED",
    EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS"
}