export enum CraneActionTypes{
    GET_CRANE = "GET_CRANE",
    GET_CRANE_FAILED = "GET_CRANE_FAILED",
    GET_CRANE_SUCCESS = "GET_CRANE_SUCCESS",

    CREATE_CRANE = "CREATE_CRANE",
    CREATE_CRANE_FAILED = "CREATE_CRANE_FAILED",
    CREATE_CRANE_SUCCESS = "CREATE_CRANE_SUCCESS",

    DELETE_CRANE = "DELETE_CRANE",
    DELETE_CRANE_FAILED = "DELETE_CRANE_FAILED",
    DELETE_CRANE_SUCCESS = "DELETE_CRANE_SUCCESS",

    EDIT_CRANE = "EDIT_CRANE",
    EDIT_CRANE_FAILED = "EDIT_CRANE_FAILED",
    EDIT_CRANE_SUCCESS = "EDIT_CRANE_SUCCESS"
}