export enum NotificationActionTypes{
    GET_NOTIFICATION = "GET_NOTIFICATION",
    GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED",
    GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS",
    DELETE_NOTIFICATION = "DELETE_NOTIFICATION"
}