export enum RolesActionTypes{
    GET_ROLES = "GET_ROLES",
    GET_ROLES_FAILED = "GET_ROLES_FAILED",
    GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS",

    CREATE_ROLE = "CREATE_ROLE",
    CREATE_ROLE_FAILED = "CREATE_ROLE_FAILED",
    CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS",


    DELETE_ROLE = "DELETE_ROLE",
    DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED",
    DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS",

    UPDATE_ROLE = "UPDATE_ROLE",
    UPDATEE_ROLE_FAILED = "UPDATE_ROLE_FAILED",
    UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS"
}