export enum RolesActionTypes{
    GET_ROLES = "GET_ROLES",
    GET_ROLES_FAILED = "GET_ROLES_FAILED",
    GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS",

    CREATE_ROLE = "CREATE_ROLE",
    CREATE_ROLE_FAILED = "CREATE_ROLE_FAILED",
    CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS"
}