export enum userActionTypes{
    GET_USERS = "GET_USERS",
    GET_USERS_FAILED = "GET_USERS_FAILED",
    GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
}

export enum createUserActionTypes{
    CREATE_USER = "CREATE_USER",
    CREATE_USER_FAILED = "CREATE_USER_FAILED",
    CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
}